version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the python consumers
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    volumes:
      - ${PWD}/src:/app
    environment:
      - DEVELOPMENT=1
      - PYTHONUNBUFFERED=true
      - KBASE_WORKSPACE_URL=http://workspace:5000
      - WORKSPACE_TOKEN=valid_admin_token

  elasticsearch:
    image: elasticsearch:6.7.0
    volumes:
      - esdata1:/usr/share/elasticsearch/data/
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:12888:13888

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
    deploy:
      resources:
        limits:
          memory: 550M

  # Mock workspace server (see src/test/mock_workspace/endpoints.json)
  workspace:
    image: mockservices/mock_json_service
    volumes:
      - ${PWD}/src/test/mock_workspace:/config

volumes:
  esdata1:
    driver: local

